###BetaVae
-   data:
        name: shapes3d
    train:
        epochs: 10
        checkpoint_every: 10
        seed: [0, 1, 2] #, 3, 4, 5, 6] #7, 8, 9]
        lr: 0.0001
        loss: betavae
    betavae:
        beta: [2, 8, 16] #[1, 2, 4, 6, 8, 16]
        